### ISSUE TITLE
List is Empty despite Multiple Scene Collections

### ISSUE THREAD

**Issue by proactivematter** [exeldro/obs-scene-collection-manager#11]
Hello,

I just installed this plugin and it doesn't populate with any of my various scene collections.

Log shows "Failed to glob scene collections"

Let me know if there is anything I can do / provide to track this down.

Many thanks

**Comment by exeldro** [comment]
What operating system? portable mode?
do you know the folder your scene collections are stored in?

**Comment by proactivematter** [comment]
MacOS 13.0.1
OBS 28.1.2 (regular)

They are located in the default folder
/Users/diego/Library/Application Support/obs-studio/basic/scenes

**Comment by exeldro** [comment]
as far as I can see now the plugin tries to read: `obs-studio/plugin_config/scene-collection-manager/../../basic/scenes/*.json`
not sure what is going wrong there

**Comment by proactivematter** [comment]
I don't have the  `obs-studio/plugin_config/scene-collection-manager` folder. Just tried reinstalling the plugin as well and relaunching OBS, but it's not there.

**Comment by exeldro** [comment]
https://github.com/exeldro/obs-scene-collection-manager/actions/runs/3552861625
Can you test if this build fixes it?

**Comment by proactivematter** [comment]
Sorry, not a dev. Tried following the build instructions but as simple as I'm sure that it is, I can't figure it out beyond step 1 (building OBS itself).

I'd be glad to test but I will need more step-by-step plugin build instructions or a release.

**Comment by exeldro** [comment]
You don't need to build it yourself, you can download the build [artifact](https://github.com/exeldro/obs-scene-collection-manager/suites/9515362455/artifacts/451785484) at the bottom of the page I linked

**Comment by proactivematter** [comment]
Ah! Thanks.

Installed it, but now OBS crashes when I try to select Scene Manager from the menu. [Here's the crash report](https://pastebin.com/NmrudJkb).

No entries on the OBS log.

**Comment by exeldro** [comment]
I made a fix, you can download the test build from the bottom of this page:
https://github.com/exeldro/obs-scene-collection-manager/actions/runs/7332084839

**Comment by proactivematter** [comment]
Awesome! All seems to be working as intended now. Damn, over a year later too. You're the man, thank you!
