### ISSUE TITLE
obs 30.0.2 on macOS m1 mac mini crashes when selecting "Scene Collection Manager" from the Tools menu

### ISSUE THREAD

**Issue by ClintCombs** [exeldro/obs-scene-collection-manager#15]
I installed the 0.1.0 release on my M1 Mac Mini and it crashes as noted in the title.

**Comment by ClintCombs** [comment]
[obs-scene-collection-crash.txt](https://github.com/exeldro/obs-scene-collection-manager/files/13772233/obs-scene-collection-crash.txt)

**Comment by exeldro** [comment]
It should try to read something like:
`/Volumes/User/me/Library/Application Support/obs-studio/basic/scenes/*.json`
is that the place scene collections are stored on mac?
On windows I am able to see the setting folder via the OBS menu File->Show Settings Folder.

**Comment by ClintCombs** [comment]
They're stored here on macOS Sonoma 14.1.2: `/Users/<username>/Library/Application Support/obs-studio/basic/scenes/*.json`

**Comment by exeldro** [comment]
I am not able to test on Mac myself. Are you able to test the build from the bottom of this page?
https://github.com/exeldro/obs-scene-collection-manager/actions/runs/7331022833
And if it does not crash, but does not load the scene collections, can you provide the OBS log file of that session?

**Comment by ClintCombs** [comment]
As you anticipated, it didn't crash and didn't load any scene collections. Here's the log file:
[2023-12-26 11-34-43.txt](https://github.com/exeldro/obs-scene-collection-manager/files/13772660/2023-12-26.11-34-43.txt)

**Comment by exeldro** [comment]
It looks like on mac `obs-studio/plugin_config/scene-collection-manager/../../basic/scenes/*.json` does not resolve to `obs-studio/basic/scenes/*.json`
new attempt here:
https://github.com/exeldro/obs-scene-collection-manager/actions/runs/7332084839

**Comment by ClintCombs** [comment]
It looks like that resolved the loading issue.
![image](https://github.com/exeldro/obs-scene-collection-manager/assets/420692/28685490-7bee-4f7c-b9b5-c75674564eef)

**Comment by exeldro** [comment]
released version 0.1.1 with this fix

**Comment by ClintCombs** [comment]
Thanks @exeldro. 👍
