### ISSUE TITLE
Feature Request: Set maximum number of backups

### ISSUE THREAD

**Issue by Fred-DTV** [exeldro/obs-scene-collection-manager#6]
Hi @exeldro 

Thanks for the life saving work haha

Just a quick idea: would it be possible to set a maximum number of backups per scene?

We have a lot of different scenes and having unlimited backups per scene will potentially result in heaps of data

**Comment by exeldro** [comment]
Should it automatic delete the oldest backups, and never the renamed ones?

**Comment by Fred-DTV** [comment]
sounds like the perfect solution :)

**Comment by exeldro** [comment]
In version 0.1.0
